# Generated by Django 4.1.4 on 2023-06-21 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_sendtransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='context',
        ),
    ]
