# Generated by Django 4.1.4 on 2023-06-21 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='channel',
            field=models.CharField(choices=[('EMAIL', 'EMAIL')], default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
