version: '3.8'

services:

  database:
    image: postgres:13
    container_name: local.database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=kabootar_user
      - POSTGRES_PASSWORD=kabootar_password
      - POSTGRES_DB=kabootar
    volumes:
      - database_data:/var/lib/postgresql/data

  kabootar-local:
    container_name: local.project
    build:
      context: ../../
      dockerfile: ./conf/local/Dockerfile
      args:
        - USER_ID=$UID
        - GROUP_ID=$GID
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - database
    volumes:
      - static_data:/vol/web
      - ../../kabootar:/app

volumes:
  static_data:
  database_data:



