version: '3.8'

services:

  database:
    image: postgres:13
    container_name: __keyword__.database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=__keyword___user
      - POSTGRES_PASSWORD=__keyword___password
      - POSTGRES_DB=__keyword___database
    volumes:
      - database_data:/var/lib/postgresql/data

  kabootar-__keyword__:
    container_name: __keyword__.project
    build:
      context: ../../
      dockerfile: ./conf/__keyword__/Dockerfile
      args:
        - USER_ID=$UID
        - GROUP_ID=$GID
    command: sh -c "pytest && uvicorn kabootar.main:app --host 0.0.0.0 --port 8000 --reload"
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - database
    volumes:
      - static_data:/vol/web
      - ../../kabootar:/app

volumes:
  static_data:
  database_data:



