# Generated by Django 4.1.4 on 2023-06-20 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templatestack',
            options={},
        ),
        migrations.RemoveField(
            model_name='templatestack',
            name='order',
        ),
        migrations.RemoveField(
            model_name='templatestack',
            name='templates',
        ),
        migrations.AddField(
            model_name='templatestack',
            name='name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TemplateStackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aws.sesemailtemplate')),
                ('template_stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.templatestack')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='templatestack',
            name='items',
            field=models.ManyToManyField(through='events.TemplateStackItem', to='aws.sesemailtemplate'),
        ),
    ]
