# Generated by Django 4.1.4 on 2023-06-20 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0001_initial'),
        ('events', '0002_alter_templatestack_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templatestackitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='event',
            name='email',
        ),
        migrations.RemoveField(
            model_name='event',
            name='template_stack',
        ),
        migrations.RemoveField(
            model_name='templatestackitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='templatestackitem',
            name='template_stack',
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='templatestackitem',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.AddField(
            model_name='templatestackitem',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='templatestackitem',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aws.sesemailtemplate'),
        ),
        migrations.DeleteModel(
            name='TemplateStack',
        ),
    ]
